export const integrantes = [
    // {
    //     nombre: "Joaquín",
    //     apellido: "González",
    //     rol: "Desarrollador Frontend",
    //     foto: "/assets/images/joaquin.jpg",
    //     github: "",
    // },
    {
        nombre: "Carlos Manuel Omar",
        apellido: "Molina",
        rol: "Desarrollador Frontend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/747895/user/icon/lambda/f1?rev=21302128",
        github: "",
    },
    {
        nombre: "Francisco Baltazar",
        apellido: "Cabrera",
        rol: "Desarrollador Frontend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/749163/user/icon/lambda/f1?rev=23348236",
        github: "",
    },
    {
        nombre: "Fabian Ismael",
        apellido: "Barrios",
        rol: "Desarrollador Frontend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/742839/user/icon/lambda/f1?rev=23612914",
        github: "",
    },
    {
        nombre: "Samuel Elias",
        apellido: "Paredes",
        rol: "Desarrollador Full Stack",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/748564/user/icon/lambda/f1?rev=26181702",
        github: "",
    },
    {
        nombre: "Mauro Isaac",
        apellido: "Torres",
        rol: "Desarrollador Backend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/744082/user/icon/lambda/f1?rev=25287784",
        github: "",
    },
	{
        nombre: "Leandro",
        apellido: "Nieto",
        rol: "Desarrollador Backend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/745504/user/icon/lambda/f1?rev=22095937",
        github: "https://github.com/yandro899",
    },
    {
        nombre: "Leonel Omar",
        apellido: "Ordoñez",
        rol: "Soporte Técnico",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/743693/user/icon/lambda/f1?rev=23452314",
        github: "",
    },
    {
        nombre: "Juan Emanuel",
        apellido: "Flores",
        rol: "Desarrollador Frontend",
        foto:  "https://virtual.unju.edu.ar/pluginfile.php/748792/user/icon/lambda/f1?rev=23338695",
        github: "",
    },
    {
        nombre: "Martin Alejandro",
        apellido: "Cala",
        rol: "Desarrollador Frontend",
        foto: "https://virtual.unju.edu.ar/pluginfile.php/736877/user/icon/lambda/f1?rev=22242026",
        github: "",
    },
];
